# Generated by Django 2.2.5 on 2020-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruncationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('truncation_step', models.FloatField(default=0.25)),
                ('rows', models.IntegerField()),
                ('image', models.ImageField(upload_to='truncation/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
