# Generated by Django 2.2.5 on 2020-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleMixModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('truncation', models.FloatField(default=1.0)),
                ('orientation', models.BooleanField()),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('image', models.ImageField(upload_to='stylemix/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
